# Generated by Django 3.2.9 on 2021-11-27 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0002_alter_topheadlinemodel_publishedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topheadlinemodel',
            name='source',
        ),
        migrations.AddField(
            model_name='topheadlinemodel',
            name='source',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiconsumer.sourcemodel'),
        ),
    ]
