# Generated by Django 3.2.9 on 2021-11-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0004_alter_topheadlinemodel_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadlinemodel',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
