# Generated by Django 3.2.9 on 2021-11-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0005_alter_topheadlinemodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topheadlinemodel',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
