# Generated by Django 3.2.9 on 2021-11-27 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiconsumer', '0005_alter_topheadlinemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsNotificationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('fail', 'Failed')], max_length=100)),
                ('createdAt', models.TimeField(auto_now_add=True)),
                ('news', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apiconsumer.topheadlinemodel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NewsFeedModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdAt', models.TimeField(auto_now_add=True)),
                ('topHeadlines', models.ManyToManyField(to='apiconsumer.TopHeadlineModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
