# Generated by Django 3.2.9 on 2021-11-28 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0001_initial'),
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsnotificationmodel',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiconsumer.topheadlinemodel'),
        ),
    ]
