# Generated by Django 3.2.9 on 2021-11-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsnotificationmodel',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
