# Generated by Django 3.2.9 on 2021-11-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0002_auto_20211127_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfeedmodel',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
