# Generated by Django 3.2.9 on 2021-11-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0005_alter_topheadlinemodel_description'),
        ('newsfeed', '0003_newsfeedmodel_updatedat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedmodel',
            name='topHeadlines',
            field=models.ManyToManyField(related_name='headlines', to='apiconsumer.TopHeadlineModel'),
        ),
    ]
