# Generated by Django 3.2.9 on 2021-11-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiconsumer', '0005_alter_topheadlinemodel_description'),
        ('newsfeed', '0004_alter_newsfeedmodel_topheadlines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsfeedmodel',
            name='topHeadlines',
            field=models.ManyToManyField(to='apiconsumer.TopHeadlineModel'),
        ),
    ]
