# Generated by Django 3.2.9 on 2021-11-28 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiconsumer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('countries', models.TextField()),
                ('keywords', models.TextField()),
                ('newsletter', models.BooleanField(default=True)),
                ('sources', models.ManyToManyField(to='apiconsumer.SourceModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
