# Generated by Django 3.2.9 on 2021-11-28 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='countries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
